{% set ruby = "ruby 3.3.3.*" %}

package:
  name: rocoto
  version: 1.3.7
source:
  git_depth: 1
  git_rev: e5a47d0
  git_url: https://github.com/christopherwharrop/rocoto.git # https://github.com/NOAA-GSL/rocoto.git
build:
  include_recipe: false
  missing_dso_whitelist:
    - "*/libruby.so.3.3"
    - "*/libxml2.so.2"
  number: 0
requirements:
  build:
    - libxml2 2.12.7.*
    - rsync
    - {{ compiler("c") }}
    - {{ ruby }}
  run:
    - {{ ruby }}
about:
  home: https://github.com/NOAA-GSL/rocoto
  license: APACHE
